function [Phi,P,Z,Kc,C]=CompensadorBisectriz(Gs,Wn,Zeta)
%[Phi,P,Z,Kc,C]=CompensadorBisectriz(Gs,Wn,Zeta)
%Zeta=-log(Mp)/(sqrt(pi^2+log(Mp)^2))
%Zeta=Sigma/Wn
%Wn=sqrt(Sigma^2+Wd^2)
%Wn=Sigma/Zeta
%Wn=4.6/(Zeta*Wn)
%Sigma=Zeta*Wn
%Sigma=4.6/Ts
%Sigma=-Wd*log(Mp)/pi
%Wd=Wn*sqrt(1-Zeta^2)
%Wd=-Sigma*pi/(log(Mp))
%Wd=sqrt(Wn^2-Sigma^2)
%Tp=pi/Wd
%Ts=4.6/Sigma
%Ts=4.6/(Zeta*Wn)
Sigma=Wn*Zeta
Wd=Wn*sqrt(1-Zeta^2)
syms s
s=-Sigma+Wd*i
Gss=tf2sym(Gs);
Phi=180-radtodeg(angle(eval(Gss))) %no puede ser mayor a 60
Theta=radtodeg(asin(Zeta))
Alpha=(90+Theta)/2
P=imag(s)/(tan(degtorad(Alpha)-degtorad(Phi)/2))-real(s)
Z=imag(s)/(tan(degtorad(Alpha)+degtorad(Phi)/2))-real(s)
C=(s+Z)/(s+P);
Kc=abs(eval(1/(Gss*C)))
s=tf('s');
C=Kc*(s+Z)/(s+P)